### ISSUE TITLE
Shouldn't ramda and ramda-adjunct be dependencies?

### ISSUE THREAD

**Issue by zcserei** [char0n/json-api-merge#86]
Since they are only peer dependencies, they are not installed and that might lead to some unexpected behaviour.

I wasn't familiar enough with how peer dependencies work so I did a bunch of digging before opening this issue, found this article particularly interesting: https://medium.com/@arturkulig/stop-using-peerdependencies-e4b55755bd16

P.S.: thanks for this neat package, it helps with something I've been doing manually for a while with rather ugly code.

**Comment by char0n** [comment]
`npm@7` is returning again to installing `peerDependencies` automatically for you. More [here](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/). The problem you describe will eventually go away with time.

> P.S.: thanks for this neat package, it helps with something I've been doing manually for a while with rather ugly code.

Yeah np. I was in the same situation and I suspected lot of people are struggling with this so I've exposed this algorithm to npm with proper tests. Glad somebody found use for it.

**Comment by frm** [comment]
This is not the case in yarn and can lead to confusion for developers. The package depends directly on both `ramda` and `ramda-adjunct`, so these shouldn't be peer dependencies, they're not optional right? Just doing `yarn add` will lead to issues. Maybe the README instructions should be to include these two when using yarn.

**Comment by char0n** [comment]
@frm yes, they are not optional. I based my decision here on my usecase, it kind of reminded me how React libraries are being distributed. But anyway you're right, there is no reason not transforming peers deps into deps. I'll release the major update of this lib with the change.

**Comment by zcserei** [comment]
Thanks for fixing this, I was also on yarn! Just updated.

**Comment by char0n** [comment]
@zcserei no, glad the library is of use to somebody
